// AUTO-GENERATED — node build.js を実行すると更新されます
const COLLECTIONS_DATA = [
  {
    "season": "2028SS",
    "folder": "collections/2028SS",
    "keyVisual": null,
    "looks": [],
    "published": false,
    "label": "2028SS",
    "kvTitle": null,
    "kvSeasonFont": null,
    "kvTitleFont": null
  },
  {
    "season": "2027SS",
    "folder": "collections/2027SS",
    "keyVisual": "top.png",
    "looks": [
      "item01.PNG",
      "item02.PNG",
      "item03.PNG",
      "item04.PNG",
      "item05.PNG",
      "item06.PNG",
      "item07.PNG",
      "item08.PNG",
      "item09.PNG",
      "item10.PNG",
      "item11.PNG",
      "item12.PNG",
      "item13.PNG",
      "item14.PNG",
      "item15.PNG",
      "item16.PNG",
      "item17.PNG",
      "item18.PNG",
      "item19.PNG",
      "item20.PNG",
      "item21.PNG",
      "item22.PNG",
      "item23.PNG",
      "item24.PNG",
      "item25.PNG",
      "item26.PNG",
      "item27.PNG",
      "item28.PNG"
    ],
    "published": false,
    "label": "2027SS",
    "kvTitle": null,
    "kvSeasonFont": null,
    "kvTitleFont": null
  },
  {
    "season": "2026-27AW",
    "folder": "collections/2026-27AW",
    "keyVisual": "top.png",
    "looks": [
      "item01.PNG",
      "item01−1.PNG",
      "item02.PNG",
      "item02−1.PNG",
      "item03.PNG",
      "item03−1.PNG",
      "item04.PNG",
      "item04−1.PNG",
      "item05.PNG",
      "item05−1.PNG",
      "item06.PNG",
      "item06−1.PNG",
      "item07.PNG",
      "item07−1.PNG",
      "item08.PNG",
      "item08−1.PNG",
      "item09.PNG",
      "item09−1.PNG",
      "item10.PNG",
      "item10−1.PNG",
      "item11.PNG",
      "item11−1.PNG",
      "item12.PNG",
      "item12−1.PNG",
      "item13.PNG",
      "item13−1.PNG",
      "item14.PNG",
      "item14−1.PNG"
    ],
    "published": false,
    "label": "2026-27AW",
    "kvTitle": null,
    "kvSeasonFont": "'Cormorant Garamond', serif",
    "kvTitleFont": null
  }
];
